// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzxxqwvkvsfeilfltcju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6eHhxd3ZrdnNmZWlsZmx0Y2p1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2NzQ4MzUsImV4cCI6MjA3ODI1MDgzNX0.ytEn1M-B8NNQjs08A_AtvHhxOXA9ukGI9IVaOOFCpt4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});